services:
  srsgnb_bladeRF:
    image: docker_srsran_bladerf
    container_name: srsgnb_bladerf
    stdin_open: true
    tty: true
    privileged: true
    devices:
      - "/dev/bus"
    volumes:
      - /dev/serial:/dev/serial:ro
      - /dev/bus/usb:/dev/bus/usb:ro
      - ./srsran_bladerf:/mnt/srsran
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=gnb
    expose:
      - "38412/sctp"
      - "2152/udp"
    networks:
      default:
        ipv4_address: ${SRS_GNB2_IP}
networks:
  default:
    name: docker_open5gs_default
    external: true
      
